name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

# 👇 这里我帮你把 # 号删掉了，系统就能认出数据库了
[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "1d76ef0e-1f44-49a8-828b-b74c4757cbba"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

# 👇 这里我帮你放开了变量，请把 example.com 换成你自己的域名！
[vars]
domain = ["mailv.cc.cd"]
jwt_secret = "suibianxie123456"

[build]
command = "npm install -g pnpm && pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
